### ISSUE TITLE
Multiple users shows up in platform

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-ui#412] opened 2017-03-31 09:01 UTC
Multiple users shows up in platform
Video link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COQjVlcUF4OGFHWmc
/view?usp=sharing

Steps to reproduce 
i have multiple accounts for testing purpose i logged in with different account one by one, and the behavior is recorded in video.

is this expected behavior ?

**Comment by hectorj2f** [comment] 2017-03-31 09:50
@naina-verma so you mention you created multiple user accounts and you can access to the others after login with one of them. Is that correct ?

**Comment by naina-verma** [comment] 2017-03-31 10:23
@hectorj2f , yes correct!

**Comment by ldimaggi** [comment] 2017-03-31 15:41
IS this a browser caching issue? Are you logging as as 2 diff users from the same machine/browser?

**Comment by mindreeper2420** [comment] 2017-03-31 15:51
this looks like you are logged in as one user, but are just looking at two different accounts (which is allowed). I'm viewing my profile while logged in, but also have Pete's account in my recent list of viewed areas.

Example below:
<img width="599" alt="screen shot 2017-03-31 at 11 49 56 am" src="https://cloud.githubusercontent.com/assets/4032718/24558182/439223b4-1608-11e7-8b44-87a036df6bd4.png">

**Comment by ldimaggi** [comment] 2017-03-31 20:52
Can a user have multiple accounts? This would make sense within the context of a team, but we don't have teams defined yet. (Can every user view areas in every other user's account?)

**Comment by pmuir** [comment] 2017-03-31 21:59
This is expected behavior at the moment, recent contexts are not currently stored in the user's profile on the backend. I am working with @sbose78 to fix this atm. Once that is fixed I will ask you to verify the problem is gone.

**Comment by rhn-support-pmuir** [comment] 2017-04-05 01:15
@naina-verma the fix went in, please verify this is now fixed for you.

**Closed** 2017-04-10 11:32 UTC
Labels: bug, important
