### ISSUE TITLE
Codebase 'undefined' created

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-ui#579] opened 2017-04-07 16:00 UTC
When you add a new codebase the popup notification contains "Codebase 'undefined' created".

**Comment by dlabrecq** [comment] 2017-04-07 17:29
Fixed.

**Comment by aslakknutsen** [comment] 2017-04-07 17:43
@dlabrecq I guess I'll take your word for it.. ;)

**Comment by dlabrecq** [comment] 2017-04-07 20:00
Fixed by https://github.com/fabric8io/fabric8-ui/pull/583

**Comment by pmuir** [comment] 2017-04-10 11:33
Dupe of #517

**Closed by pmuir** 2017-04-10 11:33 UTC
Labels: bug, important
