### ISSUE TITLE
Unable to complete registration

### ISSUE THREAD

**Issue by xcoulon** [fabric8io/fabric8-ui#1202] opened 2017-04-28 08:07 UTC
On production, I'm stuck at the registration page: 

![image](https://cloud.githubusercontent.com/assets/178502/25520003/81b16ce2-2bfa-11e7-9276-e70f8c4c8e61.png)

Clicking on the `Save Username` button results in the following error in the browser console:

````
ERROR TypeError: Cannot read property 'attributes' of undefined
    at GettingStartedService.createTransientProfile (8.54bddf8….chunk.js:1)
    at GettingStartedComponent.saveUsername (8.54bddf8….chunk.js:1)
    at Object.eval [as handleEvent] (GettingStartedComponent.ngfactory.js:1105)
    at Object._ [as handleEvent] (patternfly.css:2)
    at Object.handleEvent (patternfly.css:2)
    at dispatchEvent (patternfly.css:2)
    at patternfly.css:2
    at HTMLButtonElement.<anonymous> (patternfly.css:2)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Object.onInvokeTask (patternfly.css:2)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Zone.runTask (polyfills.f49acb8….bundle.js:1)
    at HTMLButtonElement.ZoneTask.invoke (polyfills.f49acb8….bundle.js:1)
````

Clicking on the `Connect accounts` button results in the following error in the browser console:

````
patternfly.css:2 ERROR TypeError: Cannot read property 'split' of undefined
    at ProviderService.parseJwt (8.54bddf8….chunk.js:1)
    at ProviderService.link (8.54bddf8….chunk.js:1)
    at ProviderService.linkAll (8.54bddf8….chunk.js:1)
    at GettingStartedComponent.connectAccounts (8.54bddf8….chunk.js:1)
    at Object.eval [as handleEvent] (GettingStartedComponent.ngfactory.js:1305)
    at Object._ [as handleEvent] (patternfly.css:2)
    at Object.handleEvent (patternfly.css:2)
    at dispatchEvent (patternfly.css:2)
    at patternfly.css:2
    at HTMLButtonElement.<anonymous> (patternfly.css:2)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Object.onInvokeTask (patternfly.css:2)
    at ZoneDelegate.invokeTask (polyfills.f49acb8….bundle.js:1)
    at Zone.runTask (polyfills.f49acb8….bundle.js:1)
    at HTMLButtonElement.ZoneTask.invoke (polyfills.f49acb8….bundle.js:1)
````

**Comment by xcoulon** [comment] 2017-04-28 08:58
updated the description with error message occurring when clicking on the `Save Username` button.

**Comment by dlabrecq** [comment] 2017-05-13 01:25
I'm not able to reproduce the issue on prod. However, I can harden the code to ensure the GettingStartedService.createTransientProfile() always has a User object when called (i.e., not rely on the constructor subscription).

That said, the page in this screen shot is (pre-summit) old. For example, we're no longer providing the ability to save the username -- a few changes have been made since then.

**Comment by dlabrecq** [comment] 2017-05-13 01:26
Fixed by https://github.com/fabric8io/fabric8-ui/pull/1299

**Closed** 2017-05-24 02:28 UTC
Labels: bug, important
