### ISSUE TITLE
Cannot connect GitHub account when name contains non-ASCII characters

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-ui#1285] opened 2017-05-10 14:27 UTC
1. I login to OpenShift.io
2. I'm redirected to https://openshift.io/_gettingstarted
3. I check the GitHub checkbox and click "Connect accounts" button

result:
* nothing happens in UI
* there are no HTTP requests on button click in browser console

**Comment by alexeykazakov** [comment] 2017-05-10 14:28
There is an error in Console:
```
patternfly.css:2 ERROR DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at ProviderService.parseJwt (https://openshift.io/_assets/lib/8.da26744db01c21eb11cd.chunk.js:1:8095)
    at ProviderService.link (https://openshift.io/_assets/lib/8.da26744db01c21eb11cd.chunk.js:1:7768)
    at ProviderService.linkOpenShift (https://openshift.io/_assets/lib/8.da26744db01c21eb11cd.chunk.js:1:7688)
    at GettingStartedComponent.connectAccounts (https://openshift.io/_assets/lib/8.da26744db01c21eb11cd.chunk.js:1:2815)
    at Object.eval [as handleEvent] (ng:///GettingStartedModule/GettingStartedComponent.ngfactory.js:769:24)
    at Object._ [as handleEvent] (https://openshift.io/_assets/lib/vendor.73b76953eab25ca018c6.bundle.js:1:42812)
    at Object.handleEvent (https://openshift.io/_assets/lib/vendor.73b76953eab25ca018c6.bundle.js:1:50989)
    at dispatchEvent (https://openshift.io/_assets/lib/vendor.73b76953eab25ca018c6.bundle.js:1:16557)
    at https://openshift.io/_assets/lib/vendor.73b76953eab25ca018c6.bundle.js:1:23611
    at HTMLButtonElement.<anonymous> (https://openshift.io/_assets/lib/vendor.73b76953eab25ca018c6.bundle.js:1:349435)
    at ZoneDelegate.invokeTask (https://openshift.io/_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:64817)
    at Object.onInvokeTask (https://openshift.io/_assets/lib/vendor.73b76953eab25ca018c6.bundle.js:1:93135)
    at ZoneDelegate.invokeTask (https://openshift.io/_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:64738)
    at Zone.runTask (https://openshift.io/_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:59591)
    at HTMLButtonElement.ZoneTask.invoke (https://openshift.io/_assets/lib/polyfills.f49acb8aeb061f0c40eb.bundle.js:1:65825)
```
And no calls to api.openshfit.io

**Comment by alexeykazakov** [comment] 2017-05-10 14:37
Looks like something specific to Pavol's account. I tried with other accounts and it works.
@dlabrecq any idea?

**Comment by alexeykazakov** [comment] 2017-05-10 14:42
Looks like token parsing is failing. Maybe because of "Pitoňák" (encoding) in the token claims:
```
  "name": "Pavol Pitoňák",
...
  "family_name": "Pitoňák",
```

**Comment by alexeykazakov** [comment] 2017-05-10 14:45
Yes, this is the issue ^^^. If I replace "Pitoňák" by "Pitonak" it works.

**Comment by ppitonak** [comment] 2017-05-11 10:03
Thanks @alexeykazakov, should I change the title of this issue?

**Comment by alexeykazakov** [comment] 2017-05-11 14:10
Yes please

**Comment by dlabrecq** [comment] 2017-05-12 14:54
@alexeykazakov When you say "token parsing is failing", are you speaking about the backend or the UI?

The UI calls the /login/linksession API to link GitHub and OpenShift. However, the only parsing performed by the getting started page is to extract the client_session and session_state from the auth token.

I looked at how we parse JWT tokens in the UI, but we're only pulling these two strings below. I see a preferred_username property in the token, but we're not using it here.

client_session: "eb31c188-3ed8-46a5-a648-2159319888d5"
session_state: "fbfc8492-635c-4f98-8c30-acc62eb35816"

**Comment by alexeykazakov** [comment] 2017-05-12 17:11
It's UI that is failing. See the stacktrace - https://github.com/fabric8io/fabric8-ui/issues/1285#issuecomment-300499773
`ProviderService.parseJwt (https://openshift.io/_assets/lib/8.da26744db01c21eb11cd.chunk.js:1:8095)`
It doesn't matter what you are pulling from the token actually. You parse it first and it fails.

**Comment by dlabrecq** [comment] 2017-05-13 02:11
FYI, I added the jwt-decode library for UTF-8 support. I don't have an account with UTF-8 characters, but perhaps @ppitonak can test the snapshot in the PR below?

See: https://github.com/fabric8io/fabric8-ui/pull/1300

**Comment by alexeykazakov** [comment] 2017-05-13 02:16
You could add any characters you want to your profile via https://openshift.io/<user_user_name>/_update but the profile page seems to be broken.

**Comment by dlabrecq** [comment] 2017-05-13 18:35
Yes, the _update page functionality hasn't been merged, yet. However, I was able to change my last name to Làbrécqüê via Keycloak. I even used some Japanese UTF-8 characters, but wasn't able to reproduce the original problem on Chrome. 

No errors are generated when parsing the token, before and after my fix, but I'm also not able to reproduce Caron/Hacheck accent characters using the Mac querty keyboard. Apparently, a Czech keyboard is needed to reproduce the ň character (as in Pitoňák)? I can cut/paste from here, but that may not be a proper test?

I'm keeping my fingers cross that the jwt-decode library will handle this issue -- it should handle UTF-8. If anyone can try the snapshot, perhaps with a Czech keyboard, that would be helpful.

**Comment by ppitonak** [comment] 2017-05-15 08:48
@dlabrecq I added a comment on #1300, it should be ok to copy&paste problematic unicode characters from here but it would be very strange if Japanese characters work and Slovak don't.

**Closed** 2017-05-18 04:35 UTC
Labels: important
